version: "3.9"
    
services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
      - ./sql:/sql-backup
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: aslan2001
      MYSQL_DATABASE: univer
      MYSQL_USER: root
      MYSQL_PASSWORD: aslan2001
    
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: aslan2001
      WORDPRESS_DB_NAME: univer
volumes:
  db_data: {}
  wordpress_data: {}